### ISSUE TITLE
Can't compile because of podofo

### ISSUE THREAD

**Issue by scemama** [sjg20/paperman#3]
Hi,
I am not able to compile on Bodhi LInux 2.0.0 (a lightweight Ubuntu clone),
I get:

$ make
g++ -c -m64 -pipe -g -Wall -W -D_REENTRANT -DQT_WEBKIT -DQT_QT3SUPPORT_LIB -DQT3_SUPPORT -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/Qt3Support -I/usr/include/qt4 -Iqi -I/usr/local/lib -I/usr/include/poppler/qt4 -I/usr/local/include/nuance-omnipage-csdk-15.5 -I/usr/include/podofo -I.moc -I.ui -o .obj/filepdf.o filepdf.cpp
In file included from filepdf.cpp:29:0:
pdfio.h:47:27: fatal error: podofo/podofo.h: No such file or directory
compilation terminated.
make: **\* [.obj/filepdf.o] Error 1

Thanks for your help,
Anthony
